from pydantic import BaseModel, Field
from typing import List, Optional

class SourceCitation(BaseModel):
    document_id: str
    document_name: str
    category: str
    snippet: str
    relevance_score: float = 0.92

class ChatMessage(BaseModel):
    id: str
    sender: str  # "user" or "assistant"
    text: str
    timestamp: str
    citations: List[SourceCitation] = []

class ChatRequest(BaseModel):
    message: str = Field(..., example="What is my latest WBC count and does it look normal?")
    conversation_id: Optional[str] = None
    voice_enabled: bool = False

class ChatResponse(BaseModel):
    conversation_id: str
    user_message: ChatMessage
    assistant_message: ChatMessage
    audio_base64: Optional[str] = None
    medical_disclaimer: str = (
        "DISCLAIMER: This response is generated by AI based strictly on your uploaded medical documents. "
        "It is for educational purposes only and should not be used for diagnosis or treatment."
    )
