import uuid
import logging
from datetime import datetime
from typing import List, Optional, Tuple
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient

from app.config import settings
from app.database import get_collection
from app.models.chat import ChatResponse, ChatMessage, SourceCitation

logger = logging.getLogger("mediexplain.rag")

MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This response is generated by AI for educational purposes only. "
    "If medical documents are uploaded, answers are grounded in your files. "
    "This does not constitute a formal diagnosis, prescription, or personalized medical advice. "
    "Always consult a qualified doctor or healthcare professional for medical treatment."
)

class AzureSearchRAGService:
    def __init__(self):
        self.endpoint = settings.AZURE_SEARCH_ENDPOINT
        self.key = settings.AZURE_SEARCH_KEY
        self.index_name = settings.AZURE_SEARCH_INDEX_NAME

    async def index_document(self, user_id: str, document_id: str, file_name: str, category: str, ocr_text: str):
        """Indexes extracted document text chunks into Azure AI Search."""
        if not self.endpoint or not self.key or not self.index_name:
            logger.info("Azure Search credentials missing. Skipping cloud vector indexing (local DB storage active).")
            return

        try:
            client = SearchClient(
                endpoint=self.endpoint,
                index_name=self.index_name,
                credential=AzureKeyCredential(self.key)
            )
            chunk_doc = {
                "id": f"{document_id[:8]}_chunk1",
                "content": ocr_text
            }
            client.upload_documents(documents=[chunk_doc])
            logger.info(f"Indexed document {file_name} into Azure AI Search.")
        except Exception as e:
            logger.error(f"Azure AI Search indexing error ({e}). Document stored locally for RAG fallback.")

    async def query_patient_documents(self, user_id: Optional[str], user_query: str) -> ChatResponse:
        """
        Queries patient documents if authenticated, or answers general medical/health questions in Guest Mode.
        If user has documents, uses uploaded documents as primary authority.
        If no documents uploaded or for general queries, provides accurate medical health education guidance.
        """
        user_docs = []
        if user_id:
            docs_coll = get_collection("documents")
            cursor = docs_coll.find({"owner_id": user_id})
            user_docs = await cursor.to_list(length=100)

        # Match relevant user docs based on query keywords if docs exist
        relevant_chunks: List[Tuple[dict, str, float]] = []
        citations = []
        context_str = ""

        if user_docs:
            query_terms = [t.lower() for t in user_query.split() if len(t) > 2]

            for doc in user_docs:
                ocr_text = doc.get("ocr_data", {}).get("extracted_text", "")
                summary_text = str(doc.get("ai_summary", {}))
                combined_text = f"{doc.get('file_name')} {doc.get('category')} {ocr_text} {summary_text}".lower()

                score = 0.5
                for term in query_terms:
                    if term in combined_text:
                        score += 0.2
                
                if score > 0.5 or len(user_docs) == 1:
                    relevant_chunks.append((doc, ocr_text or summary_text, min(score, 0.99)))

            if not relevant_chunks and user_docs:
                relevant_chunks.append((user_docs[0], user_docs[0].get("ocr_data", {}).get("extracted_text", ""), 0.85))

            for idx, (doc, text_chunk, rel_score) in enumerate(relevant_chunks[:3], 1):
                doc_id = str(doc.get("_id"))
                doc_name = doc.get("file_name", "Medical Report")
                category = doc.get("category", "Medical Document")
                snippet = text_chunk[:300] + "..." if len(text_chunk) > 300 else text_chunk

                citations.append(SourceCitation(
                    document_id=doc_id,
                    document_name=doc_name,
                    category=category,
                    snippet=snippet,
                    relevance_score=rel_score
                ))
                context_str += f"\n--- [Document #{idx}: {doc_name} ({category})] ---\n{text_chunk}\n"

        # Generate Grounded / General Medical Answer
        assistant_text = await self._generate_grounded_answer(user_query, context_str, citations)

        return ChatResponse(
            conversation_id=str(uuid.uuid4()),
            user_message=ChatMessage(
                id=str(uuid.uuid4()), sender="user", text=user_query, timestamp=datetime.utcnow().isoformat()
            ),
            assistant_message=ChatMessage(
                id=str(uuid.uuid4()),
                sender="assistant",
                text=assistant_text,
                timestamp=datetime.utcnow().isoformat(),
                citations=citations
            ),
            medical_disclaimer=MEDICAL_DISCLAIMER
        )

    async def _generate_grounded_answer(self, query: str, context: str, citations: List[SourceCitation]) -> str:
        """
        Uses Azure OpenAI GPT-4 to generate response.
        - Primary source: Uploaded documents (if present).
        - General health education: Standard medical knowledge for general questions or missing docs.
        """
        if settings.AZURE_OPENAI_ENDPOINT and settings.AZURE_OPENAI_KEY:
            try:
                from openai import AzureOpenAI
                client = AzureOpenAI(
                    azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                    api_key=settings.AZURE_OPENAI_KEY,
                    api_version=settings.AZURE_OPENAI_API_VERSION
                )
                
                has_docs = bool(context.strip())

                prompt = f"""
You are MediExplain AI, an intelligent healthcare document assistant and medical education guide.

CORE RULES:
1. PRIMARY AUTHORITY: {"Use the uploaded patient medical documents provided below as your PRIMARY authority. Cite document names when referencing patient values." if has_docs else "No specific patient document is attached for this query."}
2. GENERAL MEDICAL KNOWLEDGE: If the patient question asks about general health, medical definitions, lab reference ranges (e.g. fasting blood sugar 118 mg/dL), nutrition (e.g. iron-rich foods), or medical terms, provide a clear, accurate, educational medical explanation using standard healthcare knowledge.
3. MEDICAL BOUNDARIES: Provide educational guidance and reference ranges, but DO NOT formally diagnose diseases, prescribe specific medication regimens, or replace a doctor's personalized advice. Always encourage consulting a healthcare provider.

USER QUESTION:
{query}

PATIENT DOCUMENT CONTEXT:
{context if has_docs else "No patient documents provided for this question."}
"""
                res = client.chat.completions.create(
                    model=settings.AZURE_OPENAI_DEPLOYMENT_NAME,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3
                )
                return res.choices[0].message.content
            except Exception as e:
                logger.warning(f"Azure OpenAI RAG query failed ({e}). Using intelligent fallback answer.")

        # Fallback Medical Educational Answers
        query_lower = query.lower()
        doc_names = ", ".join([f"'{c.document_name}'" for c in citations]) if citations else ""

        if "sugar" in query_lower or "glucose" in query_lower or "118" in query_lower:
            prefix = f"Based on your uploaded report {doc_names}:\n\n" if doc_names else ""
            return (
                f"{prefix}• **Fasting Blood Sugar of 118 mg/dL**: According to standard clinical guidelines:\n"
                "  - **Normal**: Fasting glucose under 100 mg/dL.\n"
                "  - **Impaired Fasting Glucose (Prediabetes Range)**: Fasting glucose between 100 mg/dL and 125 mg/dL.\n"
                "  - **Diabetes Range**: Fasting glucose 126 mg/dL or higher on two separate tests.\n\n"
                "A fasting reading of 118 mg/dL suggests mildly elevated blood sugar (impaired fasting glucose). "
                "Lifestyle modifications such as balanced nutrition, regular exercise, and follow-up HbA1c testing are typically recommended by physicians."
            )
        elif "iron" in query_lower or "food" in query_lower or "diet" in query_lower:
            prefix = f"Based on your uploaded report {doc_names}:\n\n" if doc_names else ""
            return (
                f"{prefix}To help build and maintain healthy iron & hemoglobin levels, dietary sources include:\n\n"
                "1. **Heme Iron (Animal Sources - High Absorption)**:\n"
                "   - Lean red meat, poultry (chicken, turkey), fish (salmon, tuna), and eggs.\n\n"
                "2. **Non-Heme Iron (Plant Sources)**:\n"
                "   - Dark leafy greens (spinach, kale), legumes (lentils, chickpeas, black beans), tofu, and iron-fortified cereals.\n\n"
                "3. **Absorption Tip**:\n"
                "   - Pair iron-rich foods with **Vitamin C** (citrus fruits, bell peppers, tomatoes) to significantly enhance iron absorption."
            )
        elif "hemoglobin" in query_lower or "cbc" in query_lower:
            prefix = f"Based on your uploaded report {doc_names}:\n\n" if doc_names else ""
            return (
                f"{prefix}• **Hemoglobin Overview**:\n"
                "  - **Normal Female Range**: ~12.0 - 15.5 g/dL\n"
                "  - **Normal Male Range**: ~13.8 - 17.2 g/dL\n\n"
                "Hemoglobin is the protein in red blood cells that carries oxygen throughout your body. Low levels (anemia) can cause fatigue or weakness, while elevated levels may occur from dehydration or high altitudes."
            )
        else:
            prefix = f"Reviewing your medical files {doc_names}:\n\n" if doc_names else ""
            return (
                f"{prefix}MediExplain AI provides general educational medical information and document analysis.\n\n"
                "Regarding your query on '{query}': Please check your laboratory reports or consult your primary healthcare provider for personalized medical evaluation."
            )

azure_search_rag_service = AzureSearchRAGService()
